version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Install Yarn
          command: | 
            brew install yarn
            yarn --version
      - run:
          name: Install Yarn
          command: yarn install
      - run:
          name: Run tests!
          command: yarn test