version: 2.1
orbs:
  node: circleci/node@4.7
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tutorialWorkflow:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '21.2.0'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: bun